export const urlProvideAll = 'https://vapi.vnappmob.com/api/province/';
export const urlDistrict = (id) => `https://vapi.vnappmob.com/api/province/district/${id}`;
export const urlWard = (id) => `https://vapi.vnappmob.com/api/province/ward/${id}`;

export const countryPhoneMin = [
  {
    code: 'VN',
    phone: '+84',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VN.svg',
    name: 'Viet Nam',
  },
  {
    code: 'CN',
    phone: '+86',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CN.svg',
    name: 'China',
  },
  {
    code: 'US',
    phone: '+1',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/US.svg',
    name: 'United States',
  },
  {
    code: 'SG',
    phone: '+65',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SG.svg',
    name: 'Singapore',
  },
  {
    code: 'TH',
    phone: '+66',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TH.svg',
    name: 'Thailand',
  },
  {
    code: 'BR',
    phone: '+55',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BR.svg',
    name: 'Brazil',
  },
  {
    code: 'HK',
    phone: '+852',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HK.svg',
    name: 'Hong Kong',
  },
  {
    code: 'KP',
    phone: '+850',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KP.svg',
    name: 'North Korea',
  },
  {
    code: 'KR',
    phone: '+82',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KR.svg',
    name: 'Korea',
  },
  {
    code: 'JP',
    phone: '+81',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JP.svg',
    name: 'Japan',
  },
  {
    code: 'IN',
    phone: '+91',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IN.svg',
    name: 'India',
  },
  {
    code: 'ID',
    phone: '+62',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ID.svg',
    name: 'Indonesia',
  },
  {
    code: 'PH',
    phone: '+63',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PH.svg',
    name: 'Philippines',
  },
  {
    code: 'AU',
    phone: '+61',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AU.svg',
    name: 'Australia',
  },
  {
    code: 'MM',
    phone: '+95',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MM.svg',
    name: 'Myanmar',
  },
  {
    code: 'MY',
    phone: '+60',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MY.svg',
    name: 'Malaysia',
  },
  {
    code: 'LA',
    phone: '+856',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LA.svg',
    name: 'Lao',
  },
];

export const countryPhone = [
  {
    code: 'AF',
    phone: '+93',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AF.svg',
    name: 'Afghanistan',
  },
  {
    code: 'AL',
    phone: '+355',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AL.svg',
    name: 'Albania',
  },
  {
    code: 'DZ',
    phone: '+213',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DZ.svg',
    name: 'Algeria',
  },
  {
    code: 'AS',
    phone: '+1-684',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AS.svg',
    name: 'American Samoa',
  },
  {
    code: 'AD',
    phone: '+376',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AD.svg',
    name: 'Andorra',
  },
  {
    code: 'AO',
    phone: '+244',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AO.svg',
    name: 'Angola',
  },
  {
    code: 'AI',
    phone: '+1-264',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AI.svg',
    name: 'Anguilla',
  },
  {
    code: 'AQ',
    phone: '+',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AQ.svg',
    name: 'Antarctica',
  },
  {
    code: 'AG',
    phone: '+1-268',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AG.svg',
    name: 'Antigua and Barbuda',
  },
  {
    code: 'AR',
    phone: '+54',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AR.svg',
    name: 'Argentina',
  },
  {
    code: 'AM',
    phone: '+374',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AM.svg',
    name: 'Armenia',
  },
  {
    code: 'AW',
    phone: '+297',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AW.svg',
    name: 'Aruba',
  },
  {
    code: 'AU',
    phone: '+61',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AU.svg',
    name: 'Australia',
  },
  {
    code: 'AT',
    phone: '+43',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AT.svg',
    name: 'Austria',
  },
  {
    code: 'AZ',
    phone: '+994',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AZ.svg',
    name: 'Azerbaijan',
  },
  {
    code: 'BS',
    phone: '+1-242',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BS.svg',
    name: 'Bahamas',
  },
  {
    code: 'BH',
    phone: '+973',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BH.svg',
    name: 'Bahrain',
  },
  {
    code: 'BD',
    phone: '+880',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BD.svg',
    name: 'Bangladesh',
  },
  {
    code: 'BB',
    phone: '+1-246',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BB.svg',
    name: 'Barbados',
  },
  {
    code: 'BY',
    phone: '+375',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BY.svg',
    name: 'Belarus',
  },
  {
    code: 'BE',
    phone: '+32',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BE.svg',
    name: 'Belgium',
  },
  {
    code: 'BZ',
    phone: '+501',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BZ.svg',
    name: 'Belize',
  },
  {
    code: 'BJ',
    phone: '+229',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BJ.svg',
    name: 'Benin',
  },
  {
    code: 'BM',
    phone: '+1-441',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BM.svg',
    name: 'Bermuda',
  },
  {
    code: 'BT',
    phone: '+975',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BT.svg',
    name: 'Bhutan',
  },
  {
    code: 'BO',
    phone: '+591',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BO.svg',
    name: 'Bolivia, Plurinational State of',
  },
  {
    code: 'BQ',
    phone: '+599',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BQ.svg',
    name: 'Bonaire, Sint Eustatius and Saba',
  },
  {
    code: 'BA',
    phone: '+387',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BA.svg',
    name: 'Bosnia and Herzegovina',
  },
  {
    code: 'BW',
    phone: '+267',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BW.svg',
    name: 'Botswana',
  },
  {
    code: 'BR',
    phone: '+55',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BR.svg',
    name: 'Brazil',
  },
  {
    code: 'IO',
    phone: '+246',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IO.svg',
    name: 'British Indian Ocean Territory',
  },
  {
    code: 'BN',
    phone: '+673',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BN.svg',
    name: 'Brunei Darussalam',
  },
  {
    code: 'BG',
    phone: '+359',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BG.svg',
    name: 'Bulgaria',
  },
  {
    code: 'BF',
    phone: '+226',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BF.svg',
    name: 'Burkina Faso',
  },
  {
    code: 'BI',
    phone: '+257',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BI.svg',
    name: 'Burundi',
  },
  {
    code: 'KH',
    phone: '+855',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KH.svg',
    name: 'Cambodia',
  },
  {
    code: 'CM',
    phone: '+237',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CM.svg',
    name: 'Cameroon',
  },
  {
    code: 'CA',
    phone: '+1',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CA.svg',
    name: 'Canada',
  },
  {
    code: 'CV',
    phone: '+238',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CV.svg',
    name: 'Cape Verde',
  },
  {
    code: 'KY',
    phone: '+1-345',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KY.svg',
    name: 'Cayman Islands',
  },
  {
    code: 'CF',
    phone: '+236',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CF.svg',
    name: 'Central African Republic',
  },
  {
    code: 'TD',
    phone: '+235',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TD.svg',
    name: 'Chad',
  },
  {
    code: 'CL',
    phone: '+56',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CL.svg',
    name: 'Chile',
  },
  {
    code: 'CN',
    phone: '+86',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CN.svg',
    name: 'China',
  },
  {
    code: 'CX',
    phone: '+61',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CX.svg',
    name: 'Christmas Island',
  },
  {
    code: 'CC',
    phone: '+61',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CC.svg',
    name: 'Cocos (Keeling) Islands',
  },
  {
    code: 'CO',
    phone: '+57',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CO.svg',
    name: 'Colombia',
  },
  {
    code: 'KM',
    phone: '+269',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KM.svg',
    name: 'Comoros',
  },
  {
    code: 'CG',
    phone: '+242',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CG.svg',
    name: 'Congo',
  },
  {
    code: 'CD',
    phone: '+243',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CD.svg',
    name: 'Congo, the Democratic Republic of the',
  },
  {
    code: 'CK',
    phone: '+682',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CK.svg',
    name: 'Cook Islands',
  },
  {
    code: 'CR',
    phone: '+506',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CR.svg',
    name: 'Costa Rica',
  },
  {
    code: 'HR',
    phone: '+385',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HR.svg',
    name: 'Croatia',
  },
  {
    code: 'CU',
    phone: '+53',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CU.svg',
    name: 'Cuba',
  },
  {
    code: 'CW',
    phone: '+599',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CW.svg',
    name: 'Curaçao',
  },
  {
    code: 'CY',
    phone: '+357',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CY.svg',
    name: 'Cyprus',
  },
  {
    code: 'CZ',
    phone: '+420',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CZ.svg',
    name: 'Czech Republic',
  },
  {
    code: 'CI',
    phone: '+225',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CI.svg',
    name: "Côte d'Ivoire",
  },
  {
    code: 'DK',
    phone: '+45',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DK.svg',
    name: 'Denmark',
  },
  {
    code: 'DJ',
    phone: '+253',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DJ.svg',
    name: 'Djibouti',
  },
  {
    code: 'DM',
    phone: '+1-767',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DM.svg',
    name: 'Dominica',
  },
  {
    code: 'DO',
    phone: '+1-809',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DO.svg',
    name: 'Dominican Republic',
  },
  {
    code: 'EC',
    phone: '+593',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EC.svg',
    name: 'Ecuador',
  },
  {
    code: 'EG',
    phone: '+20',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EG.svg',
    name: 'Egypt',
  },
  {
    code: 'SV',
    phone: '+503',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SV.svg',
    name: 'El Salvador',
  },
  {
    code: 'GQ',
    phone: '+240',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GQ.svg',
    name: 'Equatorial Guinea',
  },
  {
    code: 'ER',
    phone: '+291',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ER.svg',
    name: 'Eritrea',
  },
  {
    code: 'EE',
    phone: '+372',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EE.svg',
    name: 'Estonia',
  },
  {
    code: 'ET',
    phone: '+251',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ET.svg',
    name: 'Ethiopia',
  },
  {
    code: 'FK',
    phone: '+500',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FK.svg',
    name: 'Falkland Islands (Malvinas)',
  },
  {
    code: 'FO',
    phone: '+298',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FO.svg',
    name: 'Faroe Islands',
  },
  {
    code: 'FJ',
    phone: '+679',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FJ.svg',
    name: 'Fiji',
  },
  {
    code: 'FI',
    phone: '+358',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FI.svg',
    name: 'Finland',
  },
  {
    code: 'FR',
    phone: '+33',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FR.svg',
    name: 'France',
  },
  {
    code: 'GF',
    phone: '+594',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GF.svg',
    name: 'French Guiana',
  },
  {
    code: 'PF',
    phone: '+689',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PF.svg',
    name: 'French Polynesia',
  },
  {
    code: 'TF',
    phone: '+',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TF.svg',
    name: 'French Southern Territories',
  },
  {
    code: 'GA',
    phone: '+241',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GA.svg',
    name: 'Gabon',
  },
  {
    code: 'GM',
    phone: '+220',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GM.svg',
    name: 'Gambia',
  },
  {
    code: 'GE',
    phone: '+995',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GE.svg',
    name: 'Georgia',
  },
  {
    code: 'DE',
    phone: '+49',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DE.svg',
    name: 'Germany',
  },
  {
    code: 'GH',
    phone: '+233',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GH.svg',
    name: 'Ghana',
  },
  {
    code: 'GI',
    phone: '+350',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GI.svg',
    name: 'Gibraltar',
  },
  {
    code: 'GR',
    phone: '+30',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GR.svg',
    name: 'Greece',
  },
  {
    code: 'GL',
    phone: '+299',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GL.svg',
    name: 'Greenland',
  },
  {
    code: 'GD',
    phone: '+1-473',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GD.svg',
    name: 'Grenada',
  },
  {
    code: 'GP',
    phone: '+590',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GP.svg',
    name: 'Guadeloupe',
  },
  {
    code: 'GU',
    phone: '+1-671',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GU.svg',
    name: 'Guam',
  },
  {
    code: 'GT',
    phone: '+502',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GT.svg',
    name: 'Guatemala',
  },
  {
    code: 'GG',
    phone: '+44-1481',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GG.svg',
    name: 'Guernsey',
  },
  {
    code: 'GN',
    phone: '+224',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GN.svg',
    name: 'Guinea',
  },
  {
    code: 'GW',
    phone: '+245',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GW.svg',
    name: 'Guinea-Bissau',
  },
  {
    code: 'GY',
    phone: '+592',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GY.svg',
    name: 'Guyana',
  },
  {
    code: 'HT',
    phone: '+509',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HT.svg',
    name: 'Haiti',
  },
  {
    code: 'VA',
    phone: '+379',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VA.svg',
    name: 'Holy See (Vatican City State)',
  },
  {
    code: 'HN',
    phone: '+504',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HN.svg',
    name: 'Honduras',
  },
  {
    code: 'HK',
    phone: '+852',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HK.svg',
    name: 'Hong Kong',
  },
  {
    code: 'HU',
    phone: '+36',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HU.svg',
    name: 'Hungary',
  },
  {
    code: 'IS',
    phone: '+354',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IS.svg',
    name: 'Iceland',
  },
  {
    code: 'IN',
    phone: '+91',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IN.svg',
    name: 'India',
  },
  {
    code: 'ID',
    phone: '+62',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ID.svg',
    name: 'Indonesia',
  },
  {
    code: 'IR',
    phone: '+98',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IR.svg',
    name: 'Iran, Islamic Republic of',
  },
  {
    code: 'IQ',
    phone: '+964',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IQ.svg',
    name: 'Iraq',
  },
  {
    code: 'IE',
    phone: '+353',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IE.svg',
    name: 'Ireland',
  },
  {
    code: 'IM',
    phone: '+44-1624',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IM.svg',
    name: 'Isle of Man',
  },
  {
    code: 'IL',
    phone: '+972',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IL.svg',
    name: 'Israel',
  },
  {
    code: 'IT',
    phone: '+39',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IT.svg',
    name: 'Italy',
  },
  {
    code: 'JM',
    phone: '+1-876',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JM.svg',
    name: 'Jamaica',
  },
  {
    code: 'JP',
    phone: '+81',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JP.svg',
    name: 'Japan',
  },
  {
    code: 'JE',
    phone: '+44-1534',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JE.svg',
    name: 'Jersey',
  },
  {
    code: 'JO',
    phone: '+962',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JO.svg',
    name: 'Jordan',
  },
  {
    code: 'KZ',
    phone: '+7',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KZ.svg',
    name: 'Kazakhstan',
  },
  {
    code: 'KE',
    phone: '+254',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KE.svg',
    name: 'Kenya',
  },
  {
    code: 'KI',
    phone: '+686',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KI.svg',
    name: 'Kiribati',
  },
  {
    code: 'KP',
    phone: '+850',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KP.svg',
    name: "Korea, Democratic People's Republic of",
  },
  {
    code: 'KR',
    phone: '+82',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KR.svg',
    name: 'Korea, Republic of',
  },
  {
    code: 'KW',
    phone: '+965',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KW.svg',
    name: 'Kuwait',
  },
  {
    code: 'KG',
    phone: '+996',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KG.svg',
    name: 'Kyrgyzstan',
  },
  {
    code: 'LA',
    phone: '+856',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LA.svg',
    name: "Lao People's Democratic Republic",
  },
  {
    code: 'LV',
    phone: '+371',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LV.svg',
    name: 'Latvia',
  },
  {
    code: 'LB',
    phone: '+961',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LB.svg',
    name: 'Lebanon',
  },
  {
    code: 'LS',
    phone: '+266',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LS.svg',
    name: 'Lesotho',
  },
  {
    code: 'LR',
    phone: '+231',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LR.svg',
    name: 'Liberia',
  },
  {
    code: 'LY',
    phone: '+218',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LY.svg',
    name: 'Libya',
  },
  {
    code: 'LI',
    phone: '+423',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LI.svg',
    name: 'Liechtenstein',
  },
  {
    code: 'LT',
    phone: '+370',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LT.svg',
    name: 'Lithuania',
  },
  {
    code: 'LU',
    phone: '+352',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LU.svg',
    name: 'Luxembourg',
  },
  {
    code: 'MO',
    phone: '+853',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MO.svg',
    name: 'Macao',
  },
  {
    code: 'MK',
    phone: '+389',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MK.svg',
    name: 'Macedonia, the Former Yugoslav Republic of',
  },
  {
    code: 'MG',
    phone: '+261',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MG.svg',
    name: 'Madagascar',
  },
  {
    code: 'MW',
    phone: '+265',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MW.svg',
    name: 'Malawi',
  },
  {
    code: 'MY',
    phone: '+60',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MY.svg',
    name: 'Malaysia',
  },
  {
    code: 'MV',
    phone: '+960',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MV.svg',
    name: 'Maldives',
  },
  {
    code: 'ML',
    phone: '+223',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ML.svg',
    name: 'Mali',
  },
  {
    code: 'MT',
    phone: '+356',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MT.svg',
    name: 'Malta',
  },
  {
    code: 'MH',
    phone: '+692',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MH.svg',
    name: 'Marshall Islands',
  },
  {
    code: 'MQ',
    phone: '+596',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MQ.svg',
    name: 'Martinique',
  },
  {
    code: 'MR',
    phone: '+222',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MR.svg',
    name: 'Mauritania',
  },
  {
    code: 'MU',
    phone: '+230',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MU.svg',
    name: 'Mauritius',
  },
  {
    code: 'YT',
    phone: '+262',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/YT.svg',
    name: 'Mayotte',
  },
  {
    code: 'MX',
    phone: '+52',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MX.svg',
    name: 'Mexico',
  },
  {
    code: 'FM',
    phone: '+691',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FM.svg',
    name: 'Micronesia, Federated States of',
  },
  {
    code: 'MD',
    phone: '+373',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MD.svg',
    name: 'Moldova, Republic of',
  },
  {
    code: 'MC',
    phone: '+377',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MC.svg',
    name: 'Monaco',
  },
  {
    code: 'MN',
    phone: '+976',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MN.svg',
    name: 'Mongolia',
  },
  {
    code: 'ME',
    phone: '+382',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ME.svg',
    name: 'Montenegro',
  },
  {
    code: 'MS',
    phone: '+1-664',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MS.svg',
    name: 'Montserrat',
  },
  {
    code: 'MA',
    phone: '+212',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MA.svg',
    name: 'Morocco',
  },
  {
    code: 'MZ',
    phone: '+258',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MZ.svg',
    name: 'Mozambique',
  },
  {
    code: 'MM',
    phone: '+95',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MM.svg',
    name: 'Myanmar',
  },
  {
    code: 'NA',
    phone: '+264',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NA.svg',
    name: 'Namibia',
  },
  {
    code: 'NR',
    phone: '+674',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NR.svg',
    name: 'Nauru',
  },
  {
    code: 'NP',
    phone: '+977',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NP.svg',
    name: 'Nepal',
  },
  {
    code: 'NL',
    phone: '+31',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NL.svg',
    name: 'Netherlands',
  },
  {
    code: 'NC',
    phone: '+687',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NC.svg',
    name: 'New Caledonia',
  },
  {
    code: 'NZ',
    phone: '+64',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NZ.svg',
    name: 'New Zealand',
  },
  {
    code: 'NI',
    phone: '+505',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NI.svg',
    name: 'Nicaragua',
  },
  {
    code: 'NE',
    phone: '+227',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NE.svg',
    name: 'Niger',
  },
  {
    code: 'NG',
    phone: '+234',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NG.svg',
    name: 'Nigeria',
  },
  {
    code: 'NU',
    phone: '+683',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NU.svg',
    name: 'Niue',
  },
  {
    code: 'NF',
    phone: '+672',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NF.svg',
    name: 'Norfolk Island',
  },
  {
    code: 'MP',
    phone: '+1-670',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MP.svg',
    name: 'Northern Mariana Islands',
  },
  {
    code: 'NO',
    phone: '+47',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NO.svg',
    name: 'Norway',
  },
  {
    code: 'OM',
    phone: '+968',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/OM.svg',
    name: 'Oman',
  },
  {
    code: 'PK',
    phone: '+92',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PK.svg',
    name: 'Pakistan',
  },
  {
    code: 'PW',
    phone: '+680',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PW.svg',
    name: 'Palau',
  },
  {
    code: 'PS',
    phone: '+970',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PS.svg',
    name: 'Palestine, State of',
  },
  {
    code: 'PA',
    phone: '+507',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PA.svg',
    name: 'Panama',
  },
  {
    code: 'PG',
    phone: '+675',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PG.svg',
    name: 'Papua New Guinea',
  },
  {
    code: 'PY',
    phone: '+595',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PY.svg',
    name: 'Paraguay',
  },
  {
    code: 'PE',
    phone: '+51',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PE.svg',
    name: 'Peru',
  },
  {
    code: 'PH',
    phone: '+63',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PH.svg',
    name: 'Philippines',
  },
  {
    code: 'PN',
    phone: '+870',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PN.svg',
    name: 'Pitcairn',
  },
  {
    code: 'PL',
    phone: '+48',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PL.svg',
    name: 'Poland',
  },
  {
    code: 'PT',
    phone: '+351',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PT.svg',
    name: 'Portugal',
  },
  {
    code: 'PR',
    phone: '+1-787',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PR.svg',
    name: 'Puerto Rico',
  },
  {
    code: 'QA',
    phone: '+974',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/QA.svg',
    name: 'Qatar',
  },
  {
    code: 'RO',
    phone: '+40',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RO.svg',
    name: 'Romania',
  },
  {
    code: 'RU',
    phone: '+7',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RU.svg',
    name: 'Russian Federation',
  },
  {
    code: 'RW',
    phone: '+250',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RW.svg',
    name: 'Rwanda',
  },
  {
    code: 'RE',
    phone: '+262',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RE.svg',
    name: 'Réunion',
  },
  {
    code: 'BL',
    phone: '+590',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BL.svg',
    name: 'Saint Barthélemy',
  },
  {
    code: 'SH',
    phone: '+290',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SH.svg',
    name: 'Saint Helena, Ascension and Tristan da Cunha',
  },
  {
    code: 'KN',
    phone: '+1-869',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KN.svg',
    name: 'Saint Kitts and Nevis',
  },
  {
    code: 'LC',
    phone: '+1-758',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LC.svg',
    name: 'Saint Lucia',
  },
  {
    code: 'MF',
    phone: '+590',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MF.svg',
    name: 'Saint Martin (French part)',
  },
  {
    code: 'PM',
    phone: '+508',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PM.svg',
    name: 'Saint Pierre and Miquelon',
  },
  {
    code: 'VC',
    phone: '+1-784',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VC.svg',
    name: 'Saint Vincent and the Grenadines',
  },
  {
    code: 'WS',
    phone: '+685',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/WS.svg',
    name: 'Samoa',
  },
  {
    code: 'SM',
    phone: '+378',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SM.svg',
    name: 'San Marino',
  },
  {
    code: 'ST',
    phone: '+239',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ST.svg',
    name: 'Sao Tome and Principe',
  },
  {
    code: 'SA',
    phone: '+966',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SA.svg',
    name: 'Saudi Arabia',
  },
  {
    code: 'SN',
    phone: '+221',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SN.svg',
    name: 'Senegal',
  },
  {
    code: 'RS',
    phone: '+381',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RS.svg',
    name: 'Serbia',
  },
  {
    code: 'SC',
    phone: '+248',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SC.svg',
    name: 'Seychelles',
  },
  {
    code: 'SL',
    phone: '+232',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SL.svg',
    name: 'Sierra Leone',
  },
  {
    code: 'SG',
    phone: '+65',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SG.svg',
    name: 'Singapore',
  },
  {
    code: 'SX',
    phone: '+599',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SX.svg',
    name: 'Sint Maarten (Dutch part)',
  },
  {
    code: 'SK',
    phone: '+421',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SK.svg',
    name: 'Slovakia',
  },
  {
    code: 'SI',
    phone: '+386',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SI.svg',
    name: 'Slovenia',
  },
  {
    code: 'SB',
    phone: '+677',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SB.svg',
    name: 'Solomon Islands',
  },
  {
    code: 'SO',
    phone: '+252',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SO.svg',
    name: 'Somalia',
  },
  {
    code: 'ZA',
    phone: '+27',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZA.svg',
    name: 'South Africa',
  },
  {
    code: 'GS',
    phone: '+',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GS.svg',
    name: 'South Georgia and the South Sandwich Islands',
  },
  {
    code: 'SS',
    phone: '+211',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SS.svg',
    name: 'South Sudan',
  },
  {
    code: 'ES',
    phone: '+34',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ES.svg',
    name: 'Spain',
  },
  {
    code: 'LK',
    phone: '+94',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LK.svg',
    name: 'Sri Lanka',
  },
  {
    code: 'SD',
    phone: '+249',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SD.svg',
    name: 'Sudan',
  },
  {
    code: 'SR',
    phone: '+597',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SR.svg',
    name: 'Suriname',
  },
  {
    code: 'SJ',
    phone: '+47',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SJ.svg',
    name: 'Svalbard and Jan Mayen',
  },
  {
    code: 'SZ',
    phone: '+268',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SZ.svg',
    name: 'Swaziland',
  },
  {
    code: 'SE',
    phone: '+46',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SE.svg',
    name: 'Sweden',
  },
  {
    code: 'CH',
    phone: '+41',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CH.svg',
    name: 'Switzerland',
  },
  {
    code: 'SY',
    phone: '+963',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SY.svg',
    name: 'Syrian Arab Republic',
  },
  {
    code: 'TW',
    phone: '+886',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TW.svg',
    name: 'Taiwan, Province of China',
  },
  {
    code: 'TJ',
    phone: '+992',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TJ.svg',
    name: 'Tajikistan',
  },
  {
    code: 'TZ',
    phone: '+255',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TZ.svg',
    name: 'Tanzania, United Republic of',
  },
  {
    code: 'TH',
    phone: '+66',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TH.svg',
    name: 'Thailand',
  },
  {
    code: 'TL',
    phone: '+670',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TL.svg',
    name: 'Timor-Leste',
  },
  {
    code: 'TG',
    phone: '+228',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TG.svg',
    name: 'Togo',
  },
  {
    code: 'TK',
    phone: '+690',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TK.svg',
    name: 'Tokelau',
  },
  {
    code: 'TO',
    phone: '+676',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TO.svg',
    name: 'Tonga',
  },
  {
    code: 'TT',
    phone: '+1-868',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TT.svg',
    name: 'Trinidad and Tobago',
  },
  {
    code: 'TN',
    phone: '+216',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TN.svg',
    name: 'Tunisia',
  },
  {
    code: 'TR',
    phone: '+90',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TR.svg',
    name: 'Turkey',
  },
  {
    code: 'TM',
    phone: '+993',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TM.svg',
    name: 'Turkmenistan',
  },
  {
    code: 'TC',
    phone: '+1-649',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TC.svg',
    name: 'Turks and Caicos Islands',
  },
  {
    code: 'TV',
    phone: '+688',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TV.svg',
    name: 'Tuvalu',
  },
  {
    code: 'UG',
    phone: '+256',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UG.svg',
    name: 'Uganda',
  },
  {
    code: 'UA',
    phone: '+380',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UA.svg',
    name: 'Ukraine',
  },
  {
    code: 'AE',
    phone: '+971',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AE.svg',
    name: 'United Arab Emirates',
  },
  {
    code: 'GB',
    phone: '+44',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GB.svg',
    name: 'United Kingdom',
  },
  {
    code: 'US',
    phone: '+1',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/US.svg',
    name: 'United States',
  },
  {
    code: 'UM',
    phone: '+1',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UM.svg',
    name: 'United States Minor Outlying Islands',
  },
  {
    code: 'UY',
    phone: '+598',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UY.svg',
    name: 'Uruguay',
  },
  {
    code: 'UZ',
    phone: '+998',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UZ.svg',
    name: 'Uzbekistan',
  },
  {
    code: 'VU',
    phone: '+678',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VU.svg',
    name: 'Vanuatu',
  },
  {
    code: 'VE',
    phone: '+58',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VE.svg',
    name: 'Venezuela, Bolivarian Republic of',
  },
  {
    code: 'VN',
    phone: '+84',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VN.svg',
    name: 'Viet Nam',
  },
  {
    code: 'VG',
    phone: '+1-284',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VG.svg',
    name: 'Virgin Islands, British',
  },
  {
    code: 'VI',
    phone: '+1-340',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VI.svg',
    name: 'Virgin Islands, U.S.',
  },
  {
    code: 'WF',
    phone: '+681',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/WF.svg',
    name: 'Wallis and Futuna',
  },
  {
    code: 'YE',
    phone: '+967',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/YE.svg',
    name: 'Yemen',
  },
  {
    code: 'ZM',
    phone: '+260',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZM.svg',
    name: 'Zambia',
  },
  {
    code: 'ZW',
    phone: '+263',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZW.svg',
    name: 'Zimbabwe',
  },
  {
    code: 'AX',
    phone: '+358-18',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AX.svg',
    name: 'Åland Islands',
  },
];
